type=item
items=diamond_sword
texture=chicken_skewer.png

#Text Formatting
nbt.display.Name=\u00a76Chicken Skewer

nbt.display.Lore.2=\u00a7aLimited Edition Item
nbt.display.Lore.3=\u00a7bCelebrating 100,000 Empire Forum Members!