type=item
items=bow
texture.bow=sharpshooter.png
texture.bow_pull_0=sharpshooter_pull_0.png
texture.bow_pull_1=sharpshooter_pull_1.png
texture.bow_pull_2=sharpshooter_pull_2.png
texture.bow_pull_3=sharpshooter_pull_3.png
texture.bow_pull_4=sharpshooter_pull_4.png

#Text Formatting
nbt.display.Name=\u00a76Sharpshooter

nbt.display.Lore.2=\u00a7aLimited Edition Item
nbt.display.Lore.3=\u00a7bCelebrating 100,000 Empire Forum Members!