type=item
model.iron_block=mcpatcher/cit/contest_awards/referral_blocks/iron_referral_block_of_clickyness
model.gold_block=mcpatcher/cit/contest_awards/referral_blocks/gold_referral_block_of_clickyness
model.diamond_block=mcpatcher/cit/contest_awards/referral_blocks/diamond_referral_block_of_clickyness

items=iron_block gold_block diamond_block

#Text Formatting
nbt.display.Name=ipattern:Referral Block of Clickyness
nbt.display.Lore.0=ipattern:Congratulations on getting the * highest amount of clicks
nbt.display.Lore.1=on your EMC referral links and banners during the month of

#September 2014, April 2015, March 2016