type=item
items=paper map
texture=thank_you_certificate.png

#Text Formatting
#nbt.display.Name=\u00a7Thank You to [Name] from Empire Minecraft
nbt.display.Lore.*=\u00a7fThis is a certificate of thanks from the

#nbt.display.Lore.*=Empire Minecraft Staff team for your continued voting
#nbt.display.Lore.*=\u00a7fefforts on the empire. Your vote helps us tremendously.