type=item
items=fishing_rod
texture.fishing_rod=voter_fishing_rod.png
texture.fishing_rod_uncast=voter_fishing_rod.png
texture.fishing_rod_cast=voter_fishing_rod_cast.png

#Text Formatting
nbt.display.Lore.*=\u00a76\u00a7l\u00a7nVoting Reward