type=item
items=bow

texture.bow=voter_bow.png
texture.bow_pull_0=voter_bow_pull_0.png
texture.bow_pull_1=voter_bow_pull_1.png
texture.bow_pull_2=voter_bow_pull_2.png
texture.bow_pull_3=voter_bow_pull_3.png
texture.bow_pull_4=voter_bow_pull_4.png

#Text Formatting
nbt.display.Lore.*=\u00a76\u00a7l\u00a7nVoting Reward