type=item
items=leather_chestplate
texture.leather_chestplate=voter_chestplate.png
texture.leather_chestplate_overlay=voter_chestplate_overlay.png

#Text Formatting
nbt.display.Lore.*=\u00a76\u00a7l\u00a7nVoting Reward