type=item
items=diamond_sword
texture=community_defender.png

#Text Formatting
nbt.display.Name=\u00a79\u00a7oCommunity Defender
nbt.display.Lore.1=A Prize awarded for our
nbt.display.Lore.2=amazing Community Member!