type=item
items=written_book
texture=new_years_aikar_signature.png

#Text Formatting
nbt.display.Name=\u00a76Happy New Years from Aikar
nbt.display.Lore.*=ipattern:\u00a7bWishing you a happy new years for *