type=item
items=written_book
texture=emc_birthday_6_aikar.png

#Text Formatting
nbt.display.Name=\u00a7dHappy 6th Birthday EMC!
nbt.display.Lore.*=\u00a75Purple People Party: 7/29/17

# 25 July 2017