type=item
items=written_book
texture=emc_birthday_6_krysyy.png

#Text Formatting
nbt.display.Name=\u00a7dEMC's 6th Birthday!
nbt.display.Lore.*=\u00a75\u00a7oPurple People Party: 7/29/17

# 25 July 2017