type=item
model.redstone_block=mcpatcher/cit/contest_awards/voter_blocks/redstone_voter_block
model.emerald_block=mcpatcher/cit/contest_awards/voter_blocks/emerald_voter_block
model.diamond_block=mcpatcher/cit/contest_awards/voter_blocks/diamond_voter_block
model.beacon=mcpatcher/cit/contest_awards/voter_blocks/voter_beacon

items=redstone_block emerald_block diamond_block beacon

#Text Formatting -- "Voter's Block"
nbt.display.Name=\u00a71V\u00a7ao\u00a74t\u00a7de\u00a79r\u00a76'\u00a7cs \u00a7eB\u00a7bl\u00a77o\u00a75c\u00a72k