type=item
items=leather_boots
texture.leather_boots=marlix_boots.png
texture.leather_boots_overlay=marlix_boots_overlay.png

#Text Formatting
#nbt.display.Name=iregex:(w|x|y|z)
nbt.display.Lore.*=\u00a7c"Forged in the depths of the Nether..."