type=item
items=diamond_sword
texture=candy_cane_sword.png

#Text Formatting
; nbt.display.Name=\u00a7lCandy Cane Sword
nbt.display.Lore.1=\u00a7c\u00a7oYou might slice your tongue off if you try to eat it.