type=item
items=spawn_egg horse_spawn_egg
texture=reindeer_egg.png
#texture.spawn_egg_overlay=reindeer_egg_overlay.png

#Text Formatting
nbt.display.Name=ipattern:*Comet*

nbt.display.Lore.*=\u00a76[ Empire Minecraft ]
#«»