type=item
items=diamond_pickaxe
texture=holiday_pick.png

#Text Formatting
nbt.display.Name=\u00a7l«\u00a7c\u00a7lHoliday Pick\u00a7f\u00a7l»

nbt.display.Lore.2=\u00a7bHappy Holidays 2013
nbt.display.Lore.3=\u00a7bfrom