type=item
items=fire_charge
texture=gold_medal.png

#Text Formatting
nbt.display.Name=ipattern:\u00a76* Gold Medal
nbt.display.Lore.0=\u00a7e\u00a7oEmpire Games 2014
nbt.display.Lore.1=\u00a7e\u00a7oArchery