type=armor
items=leather_boots
texture.leather_layer_2=voter_layer_2.png
texture.leather_layer_2_overlay=voter_layer_2_overlay.png

#Text Formatting
nbt.display.Lore.*=\u00a76\u00a7l\u00a7nVoting Reward