type=item
items=leather_leggings
texture.leather_leggings=voter_leggings.png
texture.leather_leggings_overlay=voter_leggings_overlay.png

#Text Formatting
nbt.display.Lore.*=\u00a76\u00a7l\u00a7nVoting Reward