type=item
items=leather_helmet
texture.leather_helmet=padded_fur_helmet.png
texture.leather_helmet_overlay=padded_fur_helmet_overlay.png

#Text Formatting
nbt.display.Name=\u00a7fPadded Fur Helmet
#nbt.display.Lore.*=\u00a7l\u00a7oLight, Lucky, and Thorny!