type=item
items=leather_chestplate
texture.leather_chestplate=padded_fur_chestplate.png
texture.leather_chestplate_overlay=padded_fur_chestplate_overlay.png

#Text Formatting
nbt.display.Name=\u00a7fPadded Fur Chest