type=item
items=bow

texture.bow=cupid_bow.png
texture.bow_pull_0=cupid_bow_pull_0.png
texture.bow_pull_1=cupid_bow_pull_1.png
texture.bow_pull_2=cupid_bow_pull_2.png
texture.bow_pull_3=cupid_bow_pull_3.png
texture.bow_pull_4=cupid_bow_pull_4.png

#Text Formatting
#nbt.display.Name=\u00a7dCupid's Bow
nbt.display.Lore.*=\u00a79Love is in the air!