type=item
items=red_flower red_tulip pink_tulip orange_tulip
#1.12 names:
texture.red_tulip=love_blossom.png
texture.pink_tulip=friendship_blossom.png
texture.orange_tulip=happiness_blossom.png
#1.13+ names:
texture.flower_tulip_red=love_blossom.png
texture.flower_tulip_pink=friendship_blossom.png
texture.flower_tulip_orange=happiness_blossom.png

#Text Formatting
nbt.display.Name=iregex:(Love|Friendship|Happiness) Blossom
#nbt.display.Lore.*=\u00a7e\u00a7oXXXXXX