type=armor
items=diamond_helmet diamond_chestplate diamond_leggings diamond_boots
texture.diamond_layer_1=60k_layer_1.png
texture.diamond_layer_2=60k_layer_2.png

#Text Formatting
nbt.display.Lore.2=\u00a7bLimited Edition Item
nbt.display.Lore.3=\u00a76Celebrating 60,000 Empire Members!