type=item
items=diamond_helmet
texture=big_daddy_helmet.png

#Text Formatting
nbt.display.Name=\u00a7aBig Daddy Helmet

nbt.display.Lore.2=\u00a7bLimited Edition Item
nbt.display.Lore.3=\u00a76Celebrating 60,000 Empire Members!