type=item
items=diamond_chestplate
texture=bullet_proof_vest.png

#Text Formatting
nbt.display.Name=\u00a7aBullet Proof Vest

nbt.display.Lore.2=\u00a7bLimited Edition Item
nbt.display.Lore.3=\u00a76Celebrating 60,000 Empire Members!