type=item
items=diamond_boots
texture=feather_fallllling_boots.png
#"Falling" with 5 L's

#Text Formatting
nbt.display.Name=\u00a7aFeather Fallllling Boots

nbt.display.Lore.2=\u00a7bLimited Edition Item
nbt.display.Lore.3=\u00a76Celebrating 60,000 Empire Members!