type=item
items=diamond_pickaxe
texture=ore_buster.png

#Text Formatting
nbt.display.Name=\u00a7aOre Buster

nbt.display.Lore.2=\u00a7bLimited Edition Item
nbt.display.Lore.3=\u00a76Celebrating 60,000 Empire Members!