type=item
items=bow
texture.bow=five_double_ok_bow.png
texture.bow_pull_0=five_double_ok_bow_pull_0.png
texture.bow_pull_1=five_double_ok_bow_pull_1.png
texture.bow_pull_2=five_double_ok_bow_pull_2.png
texture.bow_pull_3=five_double_ok_bow_pull_3.png
texture.bow_pull_4=five_double_ok_bow_pull_4.png

#Text Formatting -- "5-Double-'O'K Bow"
nbt.display.Name=\u00a76\u00a7l5-Double-'O'K Bow

nbt.display.Lore.4=\u00a7aLimited Edition Item Celebrating
nbt.display.Lore.5=\u00a7a500,000 Empire Minecraft Members!