type=item
items=diamond_sword
texture=god_sword.png

enchantmentIDs=mending

# Valid Example:
	# Sharpness V
	# Unbreaking III
	# Looting III
	# Knockback II
	# Fire Aspect II
	# Sweeping Edge III
	# Mending
	