type=armor
items=iron_helmet iron_chestplate iron_leggings iron_boots
texture.iron_layer_1=steel_layer_1.png
texture.iron_layer_2=steel_layer_2.png

#Text Formatting
#nbt.display.Name=iregex:(w|x|y|z)
nbt.display.Lore.*=\u00a7bEnchanted with the power of Enraged Sparks