type=item
items=pumpkin_pie
texture=pi_pie.png

#Text Formatting
nbt.display.Name=\u00a76Pi Pie
nbt.display.Lore.0=\u00a7e\u00a7oNot celebrating the ultimate
nbt.display.Lore.1=\u00a7e\u00a7opi day would be irrational!
#nbt.display.Lore.2=pi 3.14.15 pi