#Veteran's Day Promo
type=item
items=red_flower poppy
texture=remembrance_poppy.png

#Text Formatting
nbt.display.Name=\u00a74Remembrance Poppy
nbt.display.Lore.0=\u00af\u00aoHonoring all who served.
nbt.display.Lore.1=\u00af\u00aoRemembering those we lost.