#container=villager
#texture=morshu.png
#nbt.display.name=iregex:morshu

#"Lamp oil, rope? BOMBS?!"
#"You want it?! It's yours my friend, as long as you have enough rupees."
#"Sorry, Link. I can't give credit! Come back when you're a little -- mmmMMM -- richer!"
