; type=enchantment
; useGlint=false
; texture=no_glint.png
; enchantmentIDs=fire_protection

; #Text Formatting
; nbt.display.Name=iregex:\u00a7(dCupid's .*|eCooked Turkey)
; nbt.HideFlags=1

#HideFlags Syntax:
#=================
; VALUE ranges from 1 to 63 (63 combinations)
; In binary form:
; [+32][+16][+8][+4][+2][+1]

; +1 hides Enchantments
; +2 hides Attributes modifiers
; +4 hides Unbreakable
; +8 hides CanDestroy
; +16 hides CanPlaceOn
; +32 hides Others, such as potion effects & shield pattern info

; For example: "000111" has a value of 7, and it will hide Enchantments, Attribute Modifiers, and Unbreakable.