type=item
model=mcpatcher/cit/contest_awards/empire_sculptor_block
items=stone polished_andesite

#Text Formatting
nbt.display.Name=\u00a77Empire Sculptor's Block
nbt.display.Lore.*=\u00a73\u00a7o'Chisel Me This' Champion 2015