type=item
items=glass_pane
texture=empire_photographer_lens.png

#Text Formatting
nbt.display.Name=\u00a76Empire Photographer's Lens
nbt.display.Lore.3=\u00a7e\u00a7oWinner of the Thanksgiving
nbt.display.Lore.4=\u00a7e\u00a7oPicture Contest 2017