type=item
model=mcpatcher/cit/contest_awards/spooky_jack_o_lantern
items=lit_pumpkin jack_o_lantern

#Text Formatting
nbt.display.Name=\u00a76Spooky Pumpkin
nbt.display.Lore.1=\u00a75\u00a7oSpook-master of 2015!