type=item
model=mcpatcher/cit/special_events/bigdavie_pyramid_block
items=diamond_block

; #Text Formatting
nbt.display.Name=\u00a74A piece of a pyramid
nbt.display.Lore.*=\u00a73Diamond Block from \u00a7aBigdavie's \u00a73Pyramid
#([] of 3612)