type=item
items=milk_bucket
texture=t_virus_vaccine.png

#Text Formatting
nbt.display.Name=\u00a7c\u00a7l\u00a7nT Virus Vaccine

; TRIVIA: This item is based on the 'T-Virus' from the game 'Resident Evil'.