# Enraged Skeleton
skins.2=2
name.2=\u00a7cEnraged Skeleton

# Marlix - The Flying Skeleton
skins.3=3
name.3=\u00a76Marlix

# Marlix's Guardian
skins.4=4
name.4=ipattern:* Marlix's Guardian *