# Enraged Skeleton
skins.2=2
name.2=\u00a7cEnraged Wither Skeleton

# Momentus's Guardian
skins.3=3
name.3=ipattern:* Momentus's Guardian *

# Marlix's Guardian
skins.4=4
name.4=ipattern:* Marlix's Guardian *