type=item
items=leather_chestplate
texture.leather_chestplate=birthday_chestplate.png
texture.leather_chestplate_overlay=birthday_chestplate_overlay.png

#Text Formatting
#nbt.display.Name=iregex:(w|x|y|z)
nbt.display.Lore.*=\u00a7ePart of ICC Birthday Suit