# Farmer Villager
skins.2=2
professions.2=farmer:farmer

# Shepherd Villager
skins.3=3
professions.3=farmer:shepherd

# Fisherman Villager
skins.4=4
professions.4=farmer:fisherman

# Fletcher Villager
skins.5=5
professions.5=farmer:fletcher