type=item
items=leather_boots
texture.leather_boots=birthday_boots.png
texture.leather_boots_overlay=birthday_boots_overlay.png

#Text Formatting
#nbt.display.Name=iregex:(w|x|y|z)
nbt.display.Lore.*=\u00a7ePart of ICC Birthday Suit