type=item
items=carrot
texture=blizz_ard_nose.png

#Text Formatting
nbt.display.Name=\u00a74Blizz Ard's Nose
#nbt.display.Lore.0=\u00a7b\u00a7oWho nose where this nose came from. Maybe it's magic...