type=item
items=paper map
texture=permanent_derelict_protection.png

#Text Formatting
nbt.display.Name=\u00a7aPermanent Derelict Protection

nbt.display.Lore.1=\u00a73Grants the player permanent protection
nbt.display.Lore.2=\u00a73from the Derelict System, so you will never
nbt.display.Lore.3=\u00a73lose your Residence for being away.