type=item
items=paper map
texture=vault_voucher.png

#Text Formatting
nbt.display.Name=\u00a7aVault Voucher

nbt.display.Lore.1=\u00a73Gives 1 free vault page increase.
nbt.display.Lore.2=\u00a73This can let you exceed your
nbt.display.Lore.3=\u00a73max for your supporter level.
nbt.display.Lore.4=\u00a73Acquire 5 pages for free vault access.