#Easter Promo
type=item
items=rabbit_foot
texture=lucky_rabbit_foot_promo.png

#Text Formatting
nbt.display.Name=\u00a72Lucky Rabbit's Foot
nbt.display.Lore.0=\u00a76\u00a7oThis talisman glows with Leprechaun magic!