type=item
items=diamond_sword
texture=presidential_pen.png

#Text Formatting
nbt.display.Name=\u00a7cPresidential Pen
#nbt.display.Lore.*=\u00a79The shared pen of Windylava and jewel_king! EMC's Co-Presidents for a Day 2019