type=item
items=leather_boots
texture.leather_boots=pp_boots.png
texture.leather_boots_overlay=pp_boots_overlay.png

#Text Formatting
nbt.display.Name=\u00a7dPurple Power Armor
nbt.display.Lore.*=\u00a75\u00a7oPurple People Party: 7/29/17