type=item
model=mcpatcher/cit/special_events/purple_people_party/purple_power/pp_crystal
items=end_crystal

#Text Formatting
nbt.display.Name=\u00a7dPurple Power Crystal
nbt.display.Lore.*=\u00a75\u00a7oPurple People Party: 7/29/17