type=item
items=leather_leggings
texture.leather_leggings=pp_leggings.png
texture.leather_leggings_overlay=pp_leggings_overlay.png

#Text Formatting
nbt.display.Name=\u00a7dPurple Power Armor
nbt.display.Lore.*=\u00a75\u00a7oPurple People Party: 7/29/17