type=armor
items=chainmail_helmet chainmail_chestplate chainmail_leggings chainmail_boots
texture.chainmail_layer_1=emc_layer_1.png
texture.chainmail_layer_2=emc_layer_2.png

#Text Formatting
nbt.display.Name=\u00a76Empire Armor
nbt.display.Lore.*=\u00a7aCelebrating 80k Members