type=item
items=shears
texture=shear_madness.png

#Text Formatting
nbt.display.Name=\u00a76Shear Madness

nbt.display.Lore.2=\u00a7aLimited Edition Item
nbt.display.Lore.3=\u00a7bCelebrating 100,000 Empire Forum Members!