type=item
items=leather_leggings
texture.leather_leggings=padded_fur_leggings.png
texture.leather_leggings_overlay=padded_fur_leggings_overlay.png

#Text Formatting
nbt.display.Name=\u00a7fPadded Fur Leggings