type=item
items=paper
texture=instructions.png

#Text Formatting
nbt.display.Name=\u00a7b\u00a7oInstructions

#??? 
#"If you need instructions -- on how to get through the hotels, check out The Enclosed Instruction Book!"