type=item
model=mcpatcher/cit/contest_awards/carver_pumpkins/empire_carver_jack_o_lantern
items=lit_pumpkin jack_o_lantern

#Text Formatting
nbt.display.Name=\u00a76Empire Carver's Pumpkin
nbt.display.Lore.1=\u00a7e\u00a7oPumpkin Carving Champion 2017