type=item
items=leather_chestplate
texture.leather_chestplate=pp_chestplate.png
texture.leather_chestplate_overlay=pp_chestplate_overlay.png

#Text Formatting
nbt.display.Name=\u00a7dPurple Power Armor
nbt.display.Lore.*=\u00a75\u00a7oPurple People Party: 7/29/17