type=item
items=leather_leggings
texture.leather_leggings=independence_leggings.png
texture.leather_leggings_overlay=independence_leggings_overlay.png

#Text Formatting
#nbt.display.Name=iregex:(w|x|y|z)
nbt.display.Lore.1=\u00a7bCelebrating \u00a7cIndependence \u00a7fDay, \u00a792014