# Enraged Enderman
skins.2=2
name.2=\u00a7cEnraged Enderman

# Eyender - The Enderman
skins.3=3
name.3=\u00a75Eyender

# Eyender's Guardian -- Enderman
skins.4=4
name.4=ipattern:* Eyender's Guardian *