#Easter Promo
type=item
model=mcpatcher/cit/promotional_items/easter/carrot_cake_topper
items=carrot

#Text Formatting
nbt.display.Name=\u00a7eCarrot Cake Topper

nbt.display.Lore.*=\u00a76Gift from the \u00a75Easter Bunny\u00a76's child
#nbt.display.Lore.4=\u00a7d~\u00a7aCelebrating Easter 2019\u00a7d~