#Easter Promo
type=item
items=blaze_rod
texture=eggcellent_wand.png

#Text Formatting
nbt.display.Name=\u00a76Magical Eggcellent Wand

nbt.display.Lore.1=\u00a7e\u00a7o"Are YOUR eggs in a basket?"
#nbt.display.Lore.3=\u00a7aHalf off Eggification cost outside of Town