type=item
items=clock
texture=dirt_destroying_ticking_tock.png

#Text Formatting
nbt.display.Name=\u00a76\u00a7oDirt Destroying Ticking Tock

#nbt.display.Lore.3=\u00a77Redeem to an \u00a75Admin \u00a77or \u00a7aSenior Staff 
#nbt.display.Lore.4=\u00a77for one \u00a7d\u00a7lFREE Dirt Removal \u00a7r\u00a77of your \u00a7fResidence
nbt.display.Lore.*=\u00a7760x60 Residences only