type=item
items=elytra
texture.elytra=fragile_elytra.png
texture.broken_elytra=broken_fragile_elytra.png

#Text Formatting
nbt.display.Name=\u00a7fFragile Elytra
#nbt.display.Lore.0=\u00a77\u00a7lYou can fly! For a little while.