; type=item
; items=potion
; texture.potion=zombie_virus.png
; texture.potion_overlay=zombie_virus_overlay.png

; #Text Formatting
; nbt.display.Name=\u00a7aZombie Virus
; nbt.display.Lore.*=\u00a7cWARNING: DO NOT CONSUME


#=====================================================================
# Due to bugs with Optifine, this CIT has been disabled at this time.
#=====================================================================