type=item
items=flint
texture=dragon_stone_fragment.png

#Text Formatting
nbt.display.Name=\u00a75Dragon Stone Fragment
nbt.display.Lore.0=\u00a7bBroken Fragment of a Powerful Stone...
nbt.display.Lore.1=\u00a7bThe energy level is very weak.