type=item
model=mcpatcher/cit/dragon_tombs/original_dragon_egg
items=dragon_egg

; #Text Formatting
nbt.display.Name=\u00a75Original Dragon Egg
nbt.display.Lore.*=\u00a7bThis is an EMC \u00a75Original Dragon Egg