type=item
items=paper map
texture=max_res_upgrade.png

#Text Formatting
nbt.display.Name=\u00a7aMax Res Upgrade
nbt.display.Lore.1=\u00a73Increases the maximum number of Residences
nbt.display.Lore.2=\u00a73you can claim permanently by 1.
; nbt.display.Lore.3=\u00a73  Max of six per account.