type=item
items=leather_boots
texture.leather_boots=bloody_shoe.png
texture.leather_boots_overlay=bloody_shoe_overlay.png

#Text Formatting
nbt.display.Name=\u00a74\u00a7lBloody Shoe
#nbt.display.Lore.*=\u00a7c"Where'd he come from, where did he go? I miss Cotten Eyed Joe."