type=item
items=cooked_chicken
texture=cooked_turkey.png

#Text Formatting
nbt.display.Name=\u00a7eCooked Turkey
nbt.display.Lore.0=\u00a7c\u00a7o"Cluck, cluck, gobble?"
nbt.display.Lore.1=\u00a76Happy Thanksgiving!