type=item
items=cooked_beef
texture=taste_the_freedom.png

#Text Formatting
nbt.display.Name=\u00a7cTaste \u00a7fThe \u00a79Freedom
nbt.display.Lore.0=\u00a7cIndependence \u00a7fDay \u00a79Cookout.
nbt.display.Lore.1=\u00a7aLand of the Free, Home of the Steak!