type=item
items=bow

texture.bow=arena_longbow.png
texture.bow_pull_0=arena_longbow_pull_0.png
texture.bow_pull_1=arena_longbow_pull_1.png
texture.bow_pull_2=arena_longbow_pull_2.png
texture.bow_pull_3=arena_longbow_pull_3.png
texture.bow_pull_4=arena_longbow_pull_4.png

#Text Formatting
nbt.display.Name=\u00a76\u00a7oArena Longbow
nbt.display.Lore.*=\u00a76A grand Longbow won in the Arena.