type=item
items=paper map
texture=diamond_supporter_voucher.png

#Text Formatting
nbt.display.Name=\u00a73Diamond Supporter Voucher

nbt.display.Lore.1=\u00a7bCan be redeemed for 1 month of \u00a73Diamond Supporter
nbt.display.Lore.2=\u00a7bRight click while holding for redemption instructions.