type=item
items=feather
texture=empire_poet_quill.png

#Text Formatting
nbt.display.Name=\u00a7bEmpire Poet's Quill
nbt.display.Lore.0=\u00a79Winning Poet of the 2018
nbt.display.Lore.1=\u00a79EMC Poetry Contest: 'Life Changes'