type=item
items=written_book
texture=empire_cartoonist_sketchbook.png

#Text Formatting
nbt.display.Name=\u00a79Empire Cartoonist's Sketchbook
nbt.display.Lore.*=\u00a77Winner of the 2014 Comic Strip Contest