type=item
items=paper
texture=empire_author_manuscript.png

#Text Formatting
nbt.display.Name=\u00a72Empire Author's Manuscript

nbt.display.Lore.0=\u00a7aWinning Author of the March 2015 
nbt.display.Lore.1=\u00a7aEMC Adventure Map Contest:
nbt.display.Lore.2=\u00a7a'Follow the Leprechaun'