; type=item
; items=potion
; texture.potion=love_potion_9.png
; texture.potion_overlay=love_potion_9_overlay.png

; #Text Formatting
; nbt.display.Name=\u00a7dLove Potion No.9
; nbt.display.Lore.1=\u00a75New Formula. 95.2% Success Rate.


#=====================================================================
# Due to bugs with Optifine, this CIT has been disabled at this time.
#=====================================================================