type=item
model=mcpatcher/cit/contest_awards/sculpting_sand
items=sand

#Text Formatting
nbt.display.Name=\u00a76\u00a7lSculpting Sand

nbt.display.Lore.1=\u00a76Build Contest Winners: khixan & SliceOfRhyBread
nbt.display.Lore.2=\u00a7e1st Place in the Empire Minecraft 
nbt.display.Lore.3=\u00a7eSand Sculpture Extravaganza 2018