type=item
items=bow
texture.bow=lucky_bow.png
texture.bow_pull_0=lucky_bow_pull_0.png
texture.bow_pull_1=lucky_bow_pull_1.png
texture.bow_pull_2=lucky_bow_pull_2.png
texture.bow_pull_3=lucky_bow_pull_3.png
texture.bow_pull_4=lucky_bow_pull_4.png

#Text Formatting
nbt.display.Name=\u00a79Lucky Bow
#nbt.display.Lore.*=\u00a7bThank you for 7 days of Top 10 on TopG!