type=item
items=coal
texture=blizz_ard_eye.png

#Text Formatting
nbt.display.Name=\u00a74Blizz Ard's Eye
#nbt.display.Lore.0=\u00a7b\u00a7oWho nose where this nose came from. Maybe it's magic...