; type=item
; items=compass
; texture.compass_00=empire_assistant_00.png
; texture.compass_01=empire_assistant_01.png
; texture.compass_02=empire_assistant_02.png
; texture.compass_03=empire_assistant_03.png
; texture.compass_04=empire_assistant_04.png
; texture.compass_05=empire_assistant_05.png
; texture.compass_06=empire_assistant_06.png
; texture.compass_07=empire_assistant_07.png
; texture.compass_08=empire_assistant_08.png
; texture.compass_09=empire_assistant_09.png
; texture.compass_10=empire_assistant_10.png
; texture.compass_11=empire_assistant_11.png
; texture.compass_12=empire_assistant_12.png
; texture.compass_13=empire_assistant_13.png
; texture.compass_14=empire_assistant_14.png
; texture.compass_15=empire_assistant_15.png
; texture.compass_16=empire_assistant_16.png
; texture.compass_17=empire_assistant_17.png
; texture.compass_18=empire_assistant_18.png
; texture.compass_19=empire_assistant_19.png
; texture.compass_20=empire_assistant_20.png
; texture.compass_21=empire_assistant_21.png
; texture.compass_22=empire_assistant_22.png
; texture.compass_23=empire_assistant_23.png
; texture.compass_24=empire_assistant_24.png
; texture.compass_25=empire_assistant_25.png
; texture.compass_26=empire_assistant_26.png
; texture.compass_27=empire_assistant_27.png
; texture.compass_28=empire_assistant_28.png
; texture.compass_29=empire_assistant_29.png
; texture.compass_30=empire_assistant_30.png
; texture.compass_31=empire_assistant_31.png

; #Text Formatting
; nbt.display.Name=\u00a76Empire Assistant
; nbt.display.Lore.5=\u00a7aYour personal assistant to playing
; nbt.display.Lore.6=\u00a7aon \u00a76Empire Minecraft!