type=item
items=written_book
texture=second_chance.png

#Text Formatting
nbt.display.Name=\u00a76Second Chance
#nbt.display.Lore.*=You've been given a second chance. Welcome back to Empire Minecraft