type=item
items=paper map
texture=iron_supporter_gift.png

#Text Formatting
nbt.display.Name=\u00a77Supporter Gift

nbt.display.Lore.1=\u00a7aRedeem to \u00a75Maxarias \u00a7aor \u00a75IcecreamCow
nbt.display.Lore.2=\u00a7afor one month of FREE \u00a77Iron Supporter