type=item
items=bow
texture.bow=lucky_bow.png
texture.bow_pulling_0=lucky_bow_pulling_0.png
texture.bow_pulling_1=lucky_bow_pulling_1.png
texture.bow_pulling_2=lucky_bow_pulling_2.png

#Text Formatting
nbt.display.Name=\u00a79Lucky Bow
#nbt.display.Lore.*=\u00a7bThank you for 7 days of Top 10 on TopG!