type=item
items=bow

texture.bow=marlix_bow.png
texture.bow_pull_0=marlix_bow_pull_0.png
texture.bow_pull_1=marlix_bow_pull_1.png
texture.bow_pull_2=marlix_bow_pull_2.png
texture.bow_pull_3=marlix_bow_pull_3.png
texture.bow_pull_4=marlix_bow_pull_4.png

#Text Formatting
nbt.display.Name=\u00a74\u00a7lMarlix's Bow