type=item
items=leather_leggings
texture.leather_leggings=marlix_leggings.png
texture.leather_leggings_overlay=marlix_leggings_overlay.png

#Text Formatting
#nbt.display.Name=iregex:(w|x|y|z)
nbt.display.Lore.*=\u00a7c"Forged in the depths of the Nether..."