type=item
items=leather_chestplate
texture.leather_chestplate=marlix_chestplate.png
texture.leather_chestplate_overlay=marlix_chestplate_overlay.png

#Text Formatting
#nbt.display.Name=iregex:(w|x|y|z)
nbt.display.Lore.*=\u00a7c"Forged in the depths of the Nether..."