type=item
items=spawn_egg rabbit_spawn_egg
texture=chocolate_bunny_egg.png

#Text Formatting
nbt.display.Name=\u00a7dChocolate Bunny
#nbt.display.Lore.*=\u00a76Happy Easter with Chocolate Bunnies

#«»