type=item
items=spawn_egg rabbit_spawn_egg
texture=easter_bunny_egg.png

#Text Formatting
#nbt.display.Name=\u00a7aEaster Bunny

nbt.display.Lore.2=\u00a7a\u00a7oWhen Spring is in the Air
nbt.display.Lore.3=\u00a7b\u00a7oand eggs are all around,
nbt.display.Lore.4=\u00a7d\u00a7othis special hare-y friend
nbt.display.Lore.5=\u00a7e\u00a7ocomes out of the ground!

#«»