type=item
items=diamond_sword
texture=freedom_blade.png

#Text Formatting
#-- Freedom Blade (Light or Dark Red)
nbt.display.Name=iregex:(\u00a7cF\u00a7fr\u00a79e\u00a7ce\u00a7fd\u00a79o\u00a7cm \u00a7fB\u00a79l\u00a7ca\u00a7fd\u00a79e|\u00a71F\u00a7fr\u00a79e\u00a71e\u00a7fd\u00a79o\u00a71m \u00a7fB\u00a79l\u00a71a\u00a7fd\u00a79e)

nbt.display.Lore.1=\u00a7aCelebrating \u00a7cJuly \u00a7f4th, \u00a792014