type=item
items=bow

texture.bow=meteor_bow.png
texture.bow_pull_0=meteor_bow_pull_0.png
texture.bow_pull_1=meteor_bow_pull_1.png
texture.bow_pull_2=meteor_bow_pull_2.png
texture.bow_pull_3=meteor_bow_pull_3.png
texture.bow_pull_4=meteor_bow_pull_4.png

#Text Formatting
#nbt.display.Name=\u00a76Meteor Bow
nbt.display.Lore.*=\u00a79Release the stars!